name: Upload to Harvard Dataverse
on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload to Dataverse
        uses: IQSS/dataverse-uploader@v1.7
        with:
          DATAVERSE_TOKEN: ${{ secrets.DATAVERSE_TOKEN }}
          DATAVERSE_SERVER: 'https://dataverse.harvard.edu'
          DATAVERSE_DATASET_DOI: 'doi:10.7910/DVN/JI6Y97'
          PUBLISH: 'false'
